### ISSUE TITLE
works on osx; not on linux

### ISSUE THREAD

**Issue by Maxhodges** [d6u/react-container-query#47]
hi guys, any tips? I get this error when I try to run my app on a linux box. It works on osx however.

```
20170105-21:03:26.104(-6)? (STDERR) 
W20170105-21:03:26.104(-6)? (STDERR) in the root directory of your application.
W20170105-21:03:28.901(-6)? (STDERR) /home/vu/.meteor/packages/meteor-tool/.1.4.2_3.17tso1e++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20170105-21:03:28.901(-6)? (STDERR) 						throw(ex);
W20170105-21:03:28.901(-6)? (STDERR) 						^
W20170105-21:03:28.901(-6)? (STDERR) 
W20170105-21:03:28.901(-6)? (STDERR) TypeError: applyContainerQuery is not a function
W20170105-21:03:28.901(-6)? (STDERR)     at meteorInstall.imports.ui.layouts.TopMenuComponent.js (imports/ui/layouts/TopMenuComponent.js:105:36)
W20170105-21:03:28.902(-6)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:181:9)
W20170105-21:03:28.902(-6)? (STDERR)     at Module.require (packages/modules-runtime.js:106:16)
W20170105-21:03:28.902(-6)? (STDERR)     at Module.Mp.import (/home/vu/.meteor/packages/modules/.0.7.7.1m2ukcu++os+web.browser+web.cordova/npm/node_modules/reify/lib/runtime.js:70:16)
W20170105-21:03:28.902(-6)? (STDERR)     at meteorInstall.imports.ui.layouts.ConnectedTopMenuComponent.js (imports/ui/layouts/ConnectedTopMenuComponent.js:1:1)
W20170105-21:03:28.902(-6)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:181:9)
W20170105-21:03:28.902(-6)? (STDERR)     at Module.require (packages/modules-runtime.js:106:16)
W20170105-21:03:28.902(-6)? (STDERR)     at Module.Mp.import (/home/vu/.meteor/packages/modules/.0.7.7.1m2ukcu++os+web.browser+web.cordova/npm/node_modules/reify/lib/runtime.js:70:16)
W20170105-21:03:28.902(-6)? (STDERR)     at meteorInstall.imports.ui.layouts.ConnectedMasterLayout.js (/home/vu/workspace/blackship/.meteor/local/build/programs/server/app/app.js:12789:2683)
W20170105-21:03:28.902(-6)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:181:9)
W20170105-21:03:28.903(-6)? (STDERR)     at Module.require (packages/modules-runtime.js:106:16)
W20170105-21:03:28.903(-6)? (STDERR)     at Module.Mp.import (/home/vu/.meteor/packages/modules/.0.7.7.1m2ukcu++os+web.browser+web.cordova/npm/node_modules/reify/lib/runtime.js:70:16)
W20170105-21:03:28.903(-6)? (STDERR)     at meteorInstall.imports.routes.js (imports/routes.js:1:1)
W20170105-21:03:28.903(-6)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:181:9)
W20170105-21:03:28.903(-6)? (STDERR)     at Module.require (packages/modules-runtime.js:106:16)
W20170105-21:03:28.903(-6)? (STDERR)     at Module.Mp.import (/home/vu/.meteor/packages/modules/.0.7.7.1m2ukcu++os+web.browser+web.cordova/npm/node_modules/reify/lib/runtime.js:70:16)
W20170105-21:03:28.903(-6)? (STDERR)     at meteorInstall.im

```

**Comment by d6u** [comment]
Sorry. I cannot really help this. I assume this is on meteor? Maybe the import wasn't correct?

**Comment by Maxhodges** [comment]
ok yeah I guess it's something with npm or node or meteor or babel. Just thought i'd post instead it had come up before for someone. 

Cheers

**Comment by d6u** [comment]
@Maxhodges thanks for the understanding. You can post the code you used to import react-container-query, maybe someone or I can spot the problem.

**Comment by Maxhodges** [comment]
OK someone was importing like this
`import {applyContainerQuery} from 'react-container-query';`

but I've changed it to this
`import {applyContainerQuery} from 'react-container-query';`

now the error goes away!

I get a different error now, but probably unrelated
```
import {applyContainerQuery} from 'react-container-query';
...

```

Cheers!

**Comment by Maxhodges** [comment]
like this with shrinkwrap

```

"react-container-query": {
     "version": "0.6.1",
     "from": "react-container-query@>=0.6.0 <0.7.0",
     "resolved": "https://registry.npmjs.org/react-container-query/-/react-container-query-0.6.1.tgz"
   },
```

**Comment by d6u** [comment]
The newest version is 0.8.0 now, it contains breaking changes since 0.6. So the doc might be different.

**Comment by d6u** [comment]
I'm closing this because I haven't receive any updates, and I don't use meteor myself. Please reopen if you have problem.
